"""Add table InstanceStory

Revision ID: 1db34a8a2f5
Revises: 3718e3a72b2
Create Date: 2015-10-02 08:25:59.651353

"""

# revision identifiers, used by Alembic.
revision = '1db34a8a2f5'
down_revision = '3718e3a72b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('current_step_id', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('finished_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_step_id'], ['step.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance_story')
    ### end Alembic commands ###
