"""Add timestamp to story

Revision ID: 209d2dcb49a
Revises: 4f7bcbaf4ec
Create Date: 2015-09-28 12:38:01.940840

"""

# revision identifiers, used by Alembic.
revision = '209d2dcb49a'
down_revision = '4f7bcbaf4ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'timestamp')
    ### end Alembic commands ###
