"""Initial

Revision ID: 3718e3a72b2
Revises: None
Create Date: 2015-09-29 12:54:35.446842

"""

# revision identifiers, used by Alembic.
revision = '3718e3a72b2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('first_choice', sa.String(length=50), nullable=True),
    sa.Column('first_choice_step_id', sa.Integer(), nullable=True),
    sa.Column('second_choice', sa.String(length=50), nullable=True),
    sa.Column('second_choice_step_id', sa.Integer(), nullable=True),
    sa.Column('final', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['first_choice_step_id'], ['step.id'], ),
    sa.ForeignKeyConstraint(['second_choice_step_id'], ['step.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('initial_step_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['initial_step_id'], ['step.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('story')
    op.drop_table('step')
    ### end Alembic commands ###
