"""Add HistoryInstance

Revision ID: 3ad0cf4d6bc9
Revises: 1db34a8a2f5
Create Date: 2015-10-02 22:11:38.528396

"""

# revision identifiers, used by Alembic.
revision = '3ad0cf4d6bc9'
down_revision = '1db34a8a2f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('from_step_id', sa.Integer(), nullable=True),
    sa.Column('to_step_id', sa.Integer(), nullable=True),
    sa.Column('choice_text', sa.String(50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_step_id'], ['step.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instance_story.id'], ),
    sa.ForeignKeyConstraint(['to_step_id'], ['step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_instance')
    ### end Alembic commands ###
