"""Add Step model

Revision ID: ec02f5de27
Revises: 209d2dcb49a
Create Date: 2015-09-28 12:46:10.879647

"""

# revision identifiers, used by Alembic.
revision = 'ec02f5de27'
down_revision = '209d2dcb49a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('first_choice', sa.String(length=50), nullable=True),
    sa.Column('first_choice_step_id', sa.Integer(), nullable=True),
    sa.Column('second_choice', sa.String(length=50), nullable=True),
    sa.Column('second_choice_step_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_choice_step_id'], ['step.id'], ),
    sa.ForeignKeyConstraint(['second_choice_step_id'], ['step.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    ### end Alembic commands ###
